<# Generate the Android Termux config from the installed V18.8 secret. #>
[CmdletBinding()]
param([string]$Host)
$ErrorActionPreference="Stop"
$root=(Resolve-Path $PSScriptRoot).Path
$envPath=Join-Path $root ".env"
if(!(Test-Path $envPath)){throw ".env absent : lance INSTALL_MLOMEGA_V18_8_WINDOWS.ps1"}
$values=@{}
Get-Content $envPath | ForEach-Object { if($_ -notmatch '^\s*#' -and $_ -match '='){ $p=$_ -split '=',2; $values[$p[0].Trim()]=$p[1].Trim() } }
$token=[string]$values['MLOMEGA_PHONE_TOKEN']; if(!$token){throw "MLOMEGA_PHONE_TOKEN absent"}
if(!$Host){
  $tailscale=Get-Command tailscale -ErrorAction SilentlyContinue
  if($tailscale){ try{$Host=((& $tailscale.Source ip -4 2>$null | Select-Object -First 1).Trim())}catch{} }
}
if(!$Host){
  $candidate=Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue | Where-Object { $_.IPAddress -notmatch '^(127\.|169\.254\.)' -and $_.PrefixOrigin -ne 'WellKnown' } | Select-Object -First 1
  if($candidate){$Host=$candidate.IPAddress}
}
if(!$Host){throw "Impossible de détecter l'adresse PC. Passe -Host IP_TAILSCALE_DU_PC."}
$port=([uri]$values['MLOMEGA_PHONE_BRIDGE_URL']).Port; if($port -lt 1){$port=8766}
$out=Join-Path $root "MLOmega_Phone_Bridge_V18_8\android\mlomega_android_config.env.v18_8.generated"
@(
  '# Generated by MLOmega V18.8. Copy this file to ~/mlomega_android_config.env in Termux.',
  "API_BASE=\"http://$Host`:$port\"",
  "TOKEN=\"$token\"",
  'MLOMEGA_DEVICE_ID="android_phone"',
  'AUDIO_SECONDS=4', 'IMAGE_SECONDS=25', 'GPS_SECONDS=30',
  'ENABLE_AUDIO=1', 'ENABLE_IMAGES=1', 'ENABLE_GPS=1',
  'POST_SESSION_STOP=1', 'DRAIN_UPLOADS_ON_STOP=1', 'DRAIN_UPLOADS_TIMEOUT_SECONDS=180',
  'KEEP_SENT_FILES=0'
) | Set-Content $out -Encoding UTF8
Write-Host "Configuration Android générée: $out" -ForegroundColor Green
Write-Host "API: http://$Host`:$port" -ForegroundColor Green
