<#
setup_profile.ps1 — first-run capability profile assistant (handoff §3.5).

Interactive by default (Read-Host) with safe defaults; -Defaults runs
non-interactively for tests/CI. Writes configs/user_profile.yaml and also
generates configs/profiles/degraded.yaml and configs/profiles/sim.yaml,
consistent with the existing rtx3070.yaml.

PowerShell 5.1 compatible: no '&&', no ternary operators.
#>
[CmdletBinding()]
param(
  [switch]$Defaults,
  [string]$Display,
  [string]$Capture,
  [string]$Llm,
  [string]$LlmModel,
  [string]$Vision,
  [string]$Asr,
  [string]$CloudDataPolicy
)

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = (Resolve-Path (Join-Path $ScriptDir "..")).Path
Set-Location $ProjectRoot

function Ask([string]$Question, [string]$Default, [string[]]$Choices) {
  if ($Defaults) { return $Default }
  $hint = ""
  if ($Choices) { $hint = " [" + ($Choices -join "/") + "]" }
  $prompt = "$Question$hint (defaut: $Default)"
  $answer = Read-Host $prompt
  if ([string]::IsNullOrWhiteSpace($answer)) { return $Default }
  if ($Choices -and ($Choices -notcontains $answer)) {
    Write-Host "  Valeur non reconnue; on garde le defaut '$Default'." -ForegroundColor Yellow
    return $Default
  }
  return $answer
}

Write-Host "== Assistant de profil MLOmega V19 ==" -ForegroundColor Cyan
if ($Defaults) { Write-Host "(mode -Defaults non-interactif : valeurs sures)" -ForegroundColor Gray }

# --- Glasses / display ---
if (-not $Display) {
  $hasGlasses = Ask "As-tu des lunettes XR ?" "non" @("oui", "non")
  if ($hasGlasses -eq "oui") {
    $Display = Ask "Lesquelles ?" "xreal_one_pro" @("xreal_one_pro", "spectacles")
  } else {
    $Display = "phone_only"
  }
}

# --- Capture ---
if (-not $Capture) {
  $defCapture = "phone_camera"
  if ($Display -eq "xreal_one_pro") { $defCapture = "xreal_eye" }
  $Capture = Ask "Source de capture ?" $defCapture @("xreal_eye", "phone_camera", "none")
}

# --- LLM (local default) ---
if (-not $Llm) { $Llm = Ask "LLM local ou cloud ?" "ollama_local" @("ollama_local", "openai", "gemini", "anthropic") }
if (-not $LlmModel) {
  $defModel = "qwen2.5:3b-instruct-q4_K_M"
  if ($Llm -ne "ollama_local") { $defModel = "" }
  $LlmModel = Ask "Modele LLM (live)" $defModel @()
}

# --- Vision / ASR ---
if (-not $Vision) { $Vision = Ask "Vision locale ou cloud ?" "onnx_local" @("onnx_local", "cloud") }
if (-not $Asr) { $Asr = Ask "ASR local ou cloud ?" "local" @("local", "cloud") }

# --- Cloud data policy ---
if (-not $CloudDataPolicy) { $CloudDataPolicy = Ask "Politique donnees cloud" "local_only" @("local_only", "allow_crops", "allow_transcripts") }

New-Item -ItemType Directory -Force (Join-Path $ProjectRoot "configs") | Out-Null
New-Item -ItemType Directory -Force (Join-Path $ProjectRoot "configs\profiles") | Out-Null

$profilePath = Join-Path $ProjectRoot "configs\user_profile.yaml"
@"
# Generated by scripts/setup_profile.ps1 (handoff §3.5). Editable by hand.
display: $Display
capture: $Capture
llm: $Llm
llm_model: $LlmModel
vision: $Vision
asr: $Asr
cloud_data_policy: $CloudDataPolicy
"@ | Set-Content -Encoding UTF8 $profilePath
Write-Host "[OK]   Ecrit $profilePath" -ForegroundColor Green

# --- degraded.yaml (reduced cadences, coherent with rtx3070.yaml) ---
$degradedPath = Join-Path $ProjectRoot "configs\profiles\degraded.yaml"
if (-not (Test-Path $degradedPath)) {
  @"
# Degraded profile: reduced cadences under GPU/network pressure (handoff §3.6).
# Coherent with rtx3070.yaml; the GpuArbiter/degraded state machine floors here.
video:
  ingress_port: 8704
  datachannel_port: 8706
  target_resolution: 540p
  target_fps: 15
vision:
  detector_fps_min: 5
  detector_fps_max: 5
  queue_size: 1
gpu:
  max_live_vram_ratio: 0.80
  degrade_order: [detector_floor, pause_changes, refuse_vlm]
"@ | Set-Content -Encoding UTF8 $degradedPath
  Write-Host "[OK]   Ecrit $degradedPath" -ForegroundColor Green
} else {
  Write-Host "[OK]   $degradedPath deja present (conserve)" -ForegroundColor Green
}

# --- sim.yaml (simulator mode) ---
$simPath = Join-Path $ProjectRoot "configs\profiles\sim.yaml"
if (-not (Test-Path $simPath)) {
  @"
# Simulator profile: fake_xr_device + companion-web, no real hardware.
video:
  ingress_port: 8704
  datachannel_port: 8706
  target_resolution: 720p
  target_fps: 15
  source: fake_xr_device
vision:
  detector_fps_min: 5
  detector_fps_max: 10
  queue_size: 1
gpu:
  max_live_vram_ratio: 0.90
  degrade_order: [detector_floor, pause_changes, refuse_vlm]
  simulate_no_gpu: true
"@ | Set-Content -Encoding UTF8 $simPath
  Write-Host "[OK]   Ecrit $simPath" -ForegroundColor Green
} else {
  Write-Host "[OK]   $simPath deja present (conserve)" -ForegroundColor Green
}

Write-Host "`nProfil V19 configure. Verifie avec: scripts\DOCTOR_MLOMEGA_V19.ps1" -ForegroundColor Cyan
Write-Host ""
Write-Host "Etape suivante (E37) - attribution owner :" -ForegroundColor Yellow
Write-Host "  A ta premiere session, dis « configure ma voix » (ou menu -> Ma voix)." -ForegroundColor Yellow
Write-Host "  Cela enrole ta voix (porteur) : la nuit et le live t'attribuent alors" -ForegroundColor Yellow
Write-Host "  correctement tes tours de parole (speaker_person_id=owner)." -ForegroundColor Yellow
exit 0
