// <auto-generated>
// SYNCHRONISED COPY from packages/contracts/csharp/HotSceneContext.cs — DO NOT EDIT BY HAND.
// Regenerate with the Unity menu "MLOmega/Contracts/Sync from repo" (Editor/SyncContracts.cs),
// which re-copies packages/contracts/csharp/*.cs and rewrites System.Text.Json -> Newtonsoft.Json.
// Source of truth: packages/contracts/csharp (generated from packages/contracts/schemas/*.schema.json).
// Note: the source repo file also embeds a nested ReflexEvent class identical to
// ReflexEvent.cs. The sync tool removes that duplicate here to avoid a duplicate
// type in the MLOmega.Contracts.V19 namespace; this class references the shared
// ReflexEvent defined in ReflexEvent.cs.
// </auto-generated>
using System.Collections.Generic;
using Newtonsoft.Json;

namespace MLOmega.Contracts.V19
{
    public sealed class HotSceneContext
    {
        // default: v19.0
        [JsonProperty("contracts_version")]
        public string ContractsVersion { get; set; }

        [JsonProperty("session_id")]
        public string SessionId { get; set; }

        [JsonProperty("as_of")]
        public string AsOf { get; set; }

        [JsonProperty("place")]
        public Dictionary<string, object> Place { get; set; }

        // default: 0.0
        [JsonProperty("map_quality")]
        public double MapQuality { get; set; }

        [JsonProperty("focus")]
        public Dictionary<string, object> Focus { get; set; }

        [JsonProperty("visible_entities")]
        public List<Dictionary<string, object>> VisibleEntities { get; set; }

        [JsonProperty("people_identified")]
        public List<Dictionary<string, object>> PeopleIdentified { get; set; }

        [JsonProperty("activity")]
        public Dictionary<string, object> Activity { get; set; }

        [JsonProperty("translation_active")]
        public Dictionary<string, object> TranslationActive { get; set; }

        [JsonProperty("changes")]
        public List<Dictionary<string, object>> Changes { get; set; }

        [JsonProperty("reflex_events")]
        public List<ReflexEvent> ReflexEvents { get; set; }

        [JsonProperty("brain2_memory")]
        public List<Dictionary<string, object>> Brain2Memory { get; set; }

        [JsonProperty("evidence_refs")]
        public List<string> EvidenceRefs { get; set; }

        [JsonProperty("omissions")]
        public List<string> Omissions { get; set; }
    }
}
