// <auto-generated>
// Generated by packages/contracts/generate_csharp.py from schemas/EvidenceEvent.schema.json
// Do not edit by hand; regenerate instead.
// </auto-generated>
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MLOmega.Contracts.V19;

public sealed class EvidenceEvent
{
    // default: v19.0
    [JsonPropertyName("contracts_version")]
    public string ContractsVersion { get; set; }

    [JsonPropertyName("event_type")]
    public string EventType { get; set; }

    [JsonPropertyName("occurred_at")]
    public string OccurredAt { get; set; }

    [JsonPropertyName("session_id")]
    public string SessionId { get; set; }

    [JsonPropertyName("entity")]
    public Dictionary<string, object> Entity { get; set; }

    [JsonPropertyName("observation")]
    public Dictionary<string, object> Observation { get; set; }

    [JsonPropertyName("place")]
    public Dictionary<string, object> Place { get; set; }

    // enum: observed | inferred | consolidated | probable | remembered
    [JsonPropertyName("truth_level")]
    public string TruthLevel { get; set; }

    [JsonPropertyName("confidence")]
    public double Confidence { get; set; }

    [JsonPropertyName("evidence")]
    public List<Dictionary<string, object>> Evidence { get; set; }

    [JsonPropertyName("provenance")]
    public Dictionary<string, object> Provenance { get; set; }
}
