// <auto-generated>
// Generated by packages/contracts/generate_csharp.py from schemas/FrameEnvelope.schema.json
// Do not edit by hand; regenerate instead.
// </auto-generated>
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MLOmega.Contracts.V19;

public sealed class FrameEnvelope
{
    // default: v19.0
    [JsonPropertyName("contracts_version")]
    public string ContractsVersion { get; set; }

    [JsonPropertyName("session_id")]
    public string SessionId { get; set; }

    [JsonPropertyName("frame_id")]
    public string FrameId { get; set; }

    [JsonPropertyName("capture_monotonic_ns")]
    public long CaptureMonotonicNs { get; set; }

    [JsonPropertyName("captured_at_utc")]
    public string CapturedAtUtc { get; set; }

    [JsonPropertyName("pose")]
    public Pose Pose { get; set; }

    [JsonPropertyName("intrinsics")]
    public Dictionary<string, object> Intrinsics { get; set; }

    // enum: 0 | 90 | 180 | 270; default: 0
    [JsonPropertyName("rotation")]
    public long Rotation { get; set; }

    [JsonPropertyName("source")]
    public string Source { get; set; }
}

public sealed class Pose
{
    // default: v19.0
    [JsonPropertyName("contracts_version")]
    public string ContractsVersion { get; set; }

    [JsonPropertyName("position")]
    public List<double> Position { get; set; }

    [JsonPropertyName("rotation")]
    public List<double> Rotation { get; set; }
}
