// <auto-generated>
// Generated by packages/contracts/generate_csharp.py from schemas/HotSceneContext.schema.json
// Do not edit by hand; regenerate instead.
// </auto-generated>
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MLOmega.Contracts.V19;

public sealed class HotSceneContext
{
    // default: v19.0
    [JsonPropertyName("contracts_version")]
    public string ContractsVersion { get; set; }

    [JsonPropertyName("session_id")]
    public string SessionId { get; set; }

    [JsonPropertyName("as_of")]
    public string AsOf { get; set; }

    [JsonPropertyName("place")]
    public Dictionary<string, object> Place { get; set; }

    // default: 0.0
    [JsonPropertyName("map_quality")]
    public double MapQuality { get; set; }

    [JsonPropertyName("focus")]
    public Dictionary<string, object> Focus { get; set; }

    [JsonPropertyName("visible_entities")]
    public List<Dictionary<string, object>> VisibleEntities { get; set; }

    [JsonPropertyName("people_identified")]
    public List<Dictionary<string, object>> PeopleIdentified { get; set; }

    [JsonPropertyName("activity")]
    public Dictionary<string, object> Activity { get; set; }

    [JsonPropertyName("translation_active")]
    public Dictionary<string, object> TranslationActive { get; set; }

    [JsonPropertyName("changes")]
    public List<Dictionary<string, object>> Changes { get; set; }

    [JsonPropertyName("reflex_events")]
    public List<ReflexEvent> ReflexEvents { get; set; }

    [JsonPropertyName("brain2_memory")]
    public List<Dictionary<string, object>> Brain2Memory { get; set; }

    [JsonPropertyName("evidence_refs")]
    public List<string> EvidenceRefs { get; set; }

    [JsonPropertyName("omissions")]
    public List<string> Omissions { get; set; }
}

public sealed class ReflexEvent
{
    // default: v19.0
    [JsonPropertyName("contracts_version")]
    public string ContractsVersion { get; set; }

    [JsonPropertyName("session_id")]
    public string SessionId { get; set; }

    [JsonPropertyName("source_frame_id")]
    public string SourceFrameId { get; set; }

    [JsonPropertyName("skill")]
    public string Skill { get; set; }

    [JsonPropertyName("prediction")]
    public Dictionary<string, object> Prediction { get; set; }

    [JsonPropertyName("horizon_ms")]
    public long HorizonMs { get; set; }

    [JsonPropertyName("confidence")]
    public double Confidence { get; set; }

    [JsonPropertyName("severity")]
    public string Severity { get; set; }

    [JsonPropertyName("evidence_refs")]
    public List<string> EvidenceRefs { get; set; }

    [JsonPropertyName("aggregate_key")]
    public string AggregateKey { get; set; }
}
