// <auto-generated>
// Generated by packages/contracts/generate_csharp.py from schemas/LocalTrack.schema.json
// Do not edit by hand; regenerate instead.
// </auto-generated>
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MLOmega.Contracts.V19;

public sealed class LocalTrack
{
    // default: v19.0
    [JsonPropertyName("contracts_version")]
    public string ContractsVersion { get; set; }

    [JsonPropertyName("session_id")]
    public string SessionId { get; set; }

    [JsonPropertyName("track_id")]
    public string TrackId { get; set; }

    [JsonPropertyName("source_frame_id")]
    public string SourceFrameId { get; set; }

    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    [JsonPropertyName("bbox_or_mask")]
    public Dictionary<string, object> BboxOrMask { get; set; }

    [JsonPropertyName("velocity_screen")]
    public List<double> VelocityScreen { get; set; }

    [JsonPropertyName("visibility")]
    public double Visibility { get; set; }

    [JsonPropertyName("confidence")]
    public double Confidence { get; set; }

    [JsonPropertyName("observed_at_monotonic_ns")]
    public long ObservedAtMonotonicNs { get; set; }
}
