// <auto-generated>
// Generated by packages/contracts/generate_csharp.py from schemas/ReflexEvent.schema.json
// Do not edit by hand; regenerate instead.
// </auto-generated>
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MLOmega.Contracts.V19;

public sealed class ReflexEvent
{
    // default: v19.0
    [JsonPropertyName("contracts_version")]
    public string ContractsVersion { get; set; }

    [JsonPropertyName("session_id")]
    public string SessionId { get; set; }

    [JsonPropertyName("source_frame_id")]
    public string SourceFrameId { get; set; }

    [JsonPropertyName("skill")]
    public string Skill { get; set; }

    [JsonPropertyName("prediction")]
    public Dictionary<string, object> Prediction { get; set; }

    [JsonPropertyName("horizon_ms")]
    public long HorizonMs { get; set; }

    [JsonPropertyName("confidence")]
    public double Confidence { get; set; }

    [JsonPropertyName("severity")]
    public string Severity { get; set; }

    [JsonPropertyName("evidence_refs")]
    public List<string> EvidenceRefs { get; set; }

    [JsonPropertyName("aggregate_key")]
    public string AggregateKey { get; set; }
}
