// <auto-generated>
// Generated by packages/contracts/generate_csharp.py from schemas/SceneDelta.schema.json
// Do not edit by hand; regenerate instead.
// </auto-generated>
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MLOmega.Contracts.V19;

public sealed class SceneDelta
{
    // default: v19.0
    [JsonPropertyName("contracts_version")]
    public string ContractsVersion { get; set; }

    [JsonPropertyName("session_id")]
    public string SessionId { get; set; }

    [JsonPropertyName("source_frame_id")]
    public string SourceFrameId { get; set; }

    [JsonPropertyName("entities")]
    public List<Dictionary<string, object>> Entities { get; set; }

    [JsonPropertyName("relations")]
    public List<Dictionary<string, object>> Relations { get; set; }

    [JsonPropertyName("changes")]
    public List<Dictionary<string, object>> Changes { get; set; }

    // default: 0.0
    [JsonPropertyName("map_quality")]
    public double MapQuality { get; set; }

    [JsonPropertyName("evidence_refs")]
    public List<string> EvidenceRefs { get; set; }

    [JsonPropertyName("expires_at")]
    public string ExpiresAt { get; set; }
}
