// <auto-generated>
// Generated by packages/contracts/generate_csharp.py from schemas/UIIntent.schema.json
// Do not edit by hand; regenerate instead.
// </auto-generated>
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MLOmega.Contracts.V19;

public sealed class UIIntent
{
    // default: v19.0
    [JsonPropertyName("contracts_version")]
    public string ContractsVersion { get; set; }

    [JsonPropertyName("ui_intent_id")]
    public string UiIntentId { get; set; }

    // enum: ultralive | visionrt | brainlive
    [JsonPropertyName("producer")]
    public string Producer { get; set; }

    [JsonPropertyName("source_frame_id")]
    public string SourceFrameId { get; set; }

    [JsonPropertyName("target_track_id")]
    public string TargetTrackId { get; set; }

    [JsonPropertyName("entity_id")]
    public string EntityId { get; set; }

    [JsonPropertyName("component")]
    public string Component { get; set; }

    [JsonPropertyName("anchor")]
    public Dictionary<string, object> Anchor { get; set; }

    [JsonPropertyName("content")]
    public Dictionary<string, object> Content { get; set; }

    // enum: observed | probable | remembered | inferred | replay
    [JsonPropertyName("truth_level")]
    public string TruthLevel { get; set; }

    [JsonPropertyName("confidence")]
    public double Confidence { get; set; }

    [JsonPropertyName("priority")]
    public double Priority { get; set; }

    [JsonPropertyName("ttl_ms")]
    public long TtlMs { get; set; }

    [JsonPropertyName("ui_hint")]
    public Dictionary<string, object> UiHint { get; set; }

    [JsonPropertyName("evidence_refs")]
    public List<string> EvidenceRefs { get; set; }

    [JsonPropertyName("delivery_id")]
    public string DeliveryId { get; set; }
}
