// <auto-generated>
// Generated by packages/contracts/generate_csharp.py from schemas/UIReceipt.schema.json
// Do not edit by hand; regenerate instead.
// </auto-generated>
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MLOmega.Contracts.V19;

public sealed class UIReceipt
{
    // default: v19.0
    [JsonPropertyName("contracts_version")]
    public string ContractsVersion { get; set; }

    [JsonPropertyName("ui_intent_id")]
    public string UiIntentId { get; set; }

    [JsonPropertyName("delivery_id")]
    public string DeliveryId { get; set; }

    // enum: displayed | seen | acted | dismissed | corrected
    [JsonPropertyName("event")]
    public string Event { get; set; }

    [JsonPropertyName("observed_at")]
    public string ObservedAt { get; set; }

    [JsonPropertyName("local_track_state")]
    public Dictionary<string, object> LocalTrackState { get; set; }

    [JsonPropertyName("user_action")]
    public Dictionary<string, object> UserAction { get; set; }

    [JsonPropertyName("source")]
    public string Source { get; set; }
}
